name: 'deploy-build test (node)'

on: push

env:
    GH_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
    single-pkg:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: ./
              with:
                  github-token: ${{ env.GH_TOKEN }}
                  cwd: ./examples/repo

    single-pkg-build:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Build
              run: |
                  cd examples/repo-build
                  yarn build

            - uses: ./
              with:
                  github-token: ${{ env.GH_TOKEN }}
                  cwd: ./examples/repo-build

    single-pkg-custom-name:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: ./
              with:
                  github-token: ${{ env.GH_TOKEN }}
                  cwd: ./examples/repo
                  repo-name: deploy-build-test-repo-custom-name

    multiple-pkg:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install
              run: yarn install --frozen-lockfile

            - uses: ./
              with:
                  github-token: ${{ env.GH_TOKEN }}
                  cwd: ./examples/monorepo
                  repo-name: no-effect

    multiple-pkg-build:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install
              run: yarn install --frozen-lockfile

            - name: Build
              run: |
                  cd examples/monorepo-build
                  yarn build

            - uses: ./
              with:
                  github-token: ${{ env.GH_TOKEN }}
                  cwd: ./examples/monorepo-build
